### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by giangdao1402** [EinsTian1/iftd#1]
![Screenshot-from-2024-07-20-12-37-01](https://github.com/user-attachments/assets/b751c917-dc4a-4ba7-b02f-5ef284a50488)
I have encountered this issue when use catkin_make
Can you provide solution to solve it ?
Thank you !!!

**Comment by EinsTian1** [comment]
> ![Screenshot-from-2024-07-20-12-37-01](https://private-user-images.githubusercontent.com/98149078/350666690-b751c917-dc4a-4ba7-b02f-5ef284a50488.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NTU1MzMsIm5iZiI6MTcyMTQ1NTIzMywicGF0aCI6Ii85ODE0OTA3OC8zNTA2NjY2OTAtYjc1MWM5MTctZGM0YS00YmE3LWIwMmYtNWVmMjg0YTUwNDg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDA2MDAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3ZWRjMzU2NDBlM2Y2MDJmMDVhYzI2OTNjYTcxMzdkNDAxN2IyODUzNzFlYjA2ZWIzM2JmNGRiNzhhMWI0MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ku2kdKNvpqTKZvvqE32kptVyxS-ObgqUp_r4i72_Kp8) I have encountered this issue when use catkin_make Can you provide solution to solve it ? Thank you !!!

Does the version of the library file correspond to the requirements and have any relevant changes been made? I just checked the code and there is no conversion from 'const' to 'int' in the code.

**Comment by giangdao1402** [comment]
@EinsTian1 
I realized that the error occur because of xfeatures2d in opencv
How you installed opencv, i have tried different version but still the same error !

**Comment by EinsTian1** [comment]
> @EinsTian1 I realized that the error occur because of xfeatures2d in opencv How you installed opencv, i have tried different version but still the same error !

This is my small mistake. I installed two versions of OpenCV, 3.4.16 and 4.9.0, respectively. The code used OpenCV version 4.9.0, which was my small mistake when writing readme.md. And the additional contrib installed corresponds to OpenCV.

**Comment by giangdao1402** [comment]
**just remove this in cmakelist**
message("Current CPU archtecture: ${CMAKE_SYSTEM_PROCESSOR}")
if(CMAKE_SYSTEM_PROCESSOR MATCHES "(x86)|(X86)|(amd64)|(AMD64)" )
  include(ProcessorCount)
  ProcessorCount(N)
  message("Processer number:  ${N}")
  if(N GREATER 5)
    add_definitions(-DMP_EN)
    add_definitions(-DMP_PROC_NUM=4)
    message("core for MP:  4")
  elseif(N GREATER 3)
    math(EXPR PROC_NUM "${N} - 2")
    add_definitions(-DMP_EN)
    add_definitions(-DMP_PROC_NUM="${PROC_NUM}")
    message("core for MP:  ${PROC_NUM}")
  else()
    add_definitions(-DMP_PROC_NUM=1)
  endif()
else()
  add_definitions(-DMP_PROC_NUM=1)
endif()
**Now i can compile !**
