### ISSUE TITLE
Evaluation result

### ISSUE THREAD

**Issue by giangdao1402** [EinsTian1/iftd#2]
@EinsTian1 
Sorry to bother you again !
I want to ask a question:
**How can you evaluate the method ?**
Thanks !

**Comment by EinsTian1** [comment]
> @EinsTian1 Sorry to bother you again ! I want to ask a question: **How can you evaluate the method ?** Thanks !

Firstly, we need to accurately match the ground truth (GT) data with the timestamps of keyframes. If the GT distance of the detected loop is less than 15 meters, we determine it as True Positive (TP). If the GT distance of the detected loop exceeds 15 meters, we determine it as False Positive (FP), which means that the algorithm incorrectly detected the existence of the loop.
In addition, if the distance calculated by GT is less than 15 meters but the algorithm fails to detect the corresponding loop, we record this situation as False Negative (FN), indicating that the algorithm has not recognized the actual loop that exists.

**Comment by giangdao1402** [comment]
Thank you !
